export { default as Blog } from './Blogpost/Blogpost';
export { Order } from './Order/Order';
export { OrderDetail } from './Order/OrderDetail';
export { ContactUs } from './ContactUs/ContactUs';
export { Admin } from './Admin/Admin';
export { default as UserInfo } from './User/UserInfo';
export { default as Home } from './Home/Home';
export { default as Voucher } from './Vouchers/Voucher';
export { default as Cart } from './Cart/Cart';
export { default as ShipDetail } from './ShipDetail/ShipDetail';
export { default as Blogpost } from './Blogpost/Blogpost';
export { default as PaymentSuccess } from './Payment/PaymentSuccess';
export { default as ManageVoucher } from './Dashboard/Voucher/ManageVoucher';

export { default as Category } from './Product/Category';
export { default as Foundation } from './Product/Foundation';
export { default as MakeupBase } from './Product/MakeupBase';
export { default as PowerPact } from './Product/PowerPact';
export { default as Concealer } from './Product/Concealer';
export { default as Cushion } from './Product/Cushion';
export { default as BlusherHighlighter } from './Product/BlusherHighlighter';
